### ISSUE TITLE
Memory leak on large modpack

### ISSUE THREAD

**Issue by Dakedres** [MoonManModding/EmergingTechnology#64] opened 2020-02-25 03:52 UTC
I tried adding this to my pack and encountered a memory leak a bit into game play, all I had done with the mod was look at some of the machines and power a biomass generator when the RAM started 
filling up.

[Log](https://gist.github.com/Dakedres/dca84725dd364b7e35f20c5833bb85b7)
[Modlist](https://gist.github.com/Dakedres/456a1739ed783b82d618118bde0f81cd)
Screenshot:
![image](https://user-images.githubusercontent.com/36781227/75213162-85a91780-5746-11ea-99c7-c55ead217393.png)

Please note that it usually only sits around 2500mb of memory usage; not once have I seen it get this high under normal circumstances.

**Comment by MoonManModding** [comment] 2020-02-25 10:23
Hi,

Thanks for reporting this 😁

Apart from the Biomass Generator, which machines were you using? Was it just machines from Emerging Technology or a combination with other mods?

There doesn't seem to be anything obvious in the logs you provided but if I can reproduce it with the same machines I'll see what I can do.

Thanks again!

**Comment by Dakedres** [comment] 2020-02-27 21:22
Sorry, I totally forgot about this, I've been really busy with life things.

I was not really using it alongside any mods; I was just looking at some of the machines' functionality. The only cross-mod thing I think I attempted was putting Rich Phyto-grow from Thermal Foundation in the Generator, which didn't work obviously. After interacting with the machine the log started spitting out huge chunks of text which I only now realise are empty from that log, but luckily I did capture a screenshot that I had sent to on Discord.
![image](https://cdn.discordapp.com/attachments/166630061217153024/681707412322910210/unknown.png)
I don't know why I didn't mention this. I thought you'd notice them in the log but now I remembered I actually was able to close out of the game which would bury them quite a bit.

**Comment by MoonManModding** [comment] 2020-02-27 21:38
Hm, not sure about this one. In your original logs the mod **pegbeard.dungeontactics** seems to be throwing up errors pretty much constantly but I'm not sure if that's the cause.

Are you running a server? Would it be possible to remove all mods except Emerging Technology on its own or with Thermal and see if the issue persists?

Thank you again 👍

**Comment by Dakedres** [comment] 2020-02-29 19:48
Yeah I could try and recreate it in a more isolated environment, might take me a while to get back though. Life stuff.

**Comment by MoonManModding** [comment] 2020-02-29 20:50
No problemo, whenever you get a chance 👍

(Going to close this temporarily)

**Closed as completed** 2020-03-01 17:56 UTC
Labels: Awaiting user, Mod Interaction Bug

**Comment by Dakedres** [comment] 2020-03-22 08:12
Almost a month later. Sorry, kinda forgot about this. The issue I found persisted even without ET and took like a week to fix, but was in no way caused by it. My bad, sorry for all the hassle. You can completely forget about this.

**Comment by MoonManModding** [comment] 2020-03-22 14:09
No problem at all 😊 Thanks for checking and getting back to me. Let me know if you have any other issues.
